import {
  faArrowRight,
  faArrowRightToBracket,
  faArrowUpRightFromSquare,
  faBell,
  faBook,
  faBookOpen,
  faBriefcase,
  faCertificate,
  faCheck,
  faCircleCheck,
  faCircleInfo,
  faCode,
  faCodeBranch,
  faCodePullRequest,
  faComments,
  faCrown,
  faGraduationCap,
  faGripVertical,
  faHeading,
  faHeart,
  faImage,
  faKey,
  faLanguage,
  faListCheck,
  faMobileScreen,
  faParagraph,
  faPeopleGroup,
  faPlus,
  faQuoteLeft,
  faRocket,
  faRoute,
  faScaleBalanced,
  faServer,
  faSliders,
  faTerminal,
  faTrophy,
  faUserGraduate,
} from "@fortawesome/free-solid-svg-icons";
import {
  faDocker,
  faGithub,
} from "@fortawesome/free-brands-svg-icons";
import { faCopy } from "@fortawesome/free-regular-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const ICONS = {
  "arrow-right": faArrowRight,
  "arrow-into": faArrowRightToBracket,
  "arrow-out": faArrowUpRightFromSquare,
  bell: faBell,
  book: faBook,
  "book-open": faBookOpen,
  briefcase: faBriefcase,
  certificate: faCertificate,
  check: faCheck,
  "circle-check": faCircleCheck,
  "circle-info": faCircleInfo,
  code: faCode,
  "code-branch": faCodeBranch,
  "code-pr": faCodePullRequest,
  comments: faComments,
  copy: faCopy,
  crown: faCrown,
  docker: faDocker,
  github: faGithub,
  graduation: faGraduationCap,
  grip: faGripVertical,
  heading: faHeading,
  heart: faHeart,
  image: faImage,
  key: faKey,
  language: faLanguage,
  "list-check": faListCheck,
  mobile: faMobileScreen,
  paragraph: faParagraph,
  people: faPeopleGroup,
  plus: faPlus,
  quote: faQuoteLeft,
  rocket: faRocket,
  route: faRoute,
  scale: faScaleBalanced,
  server: faServer,
  sliders: faSliders,
  terminal: faTerminal,
  trophy: faTrophy,
  "user-graduate": faUserGraduate,
} as const satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof ICONS;
